trainer:
  cwd: /home/ # working directory
  logger: CNNS # logger name
  epochs: 100 # number of training epochs
  seed: 123 # randomness seed
  cuda: True # use nvidia gpu
  gpu: 1 # id of gpu
  shape: 224
  save: True # save checkpoint
  load: True # load pretrained checkpoint
  gradient_accumulation: 32 # gradient accumulation steps
  batch_size: 16
  pretrained_cpkt: /home/papastrat/PycharmProjects/CNNs/checkpoints/dataset_celeba/model_pit/date_03_05_2021_17.17.42/_model_last_checkpoint.pth.tar
  log_interval: 10000 # print statistics every log_interval
  model:
    name: pit # model name  [mobilenet_v2,COVIDNet_small]
    pretrained: False
    optimizer: # optimizer configuration
      type: Adam # optimizer type
      lr: 1e-3 # learning rate
      weight_decay: 0.00001 # weight decay
    scheduler: # learning rate scheduler
      type: ReduceLRonPlateau # type of scheduler
      scheduler_factor: 0.5 # learning rate change ratio
      scheduler_patience: 0 # patience for some epochs
      scheduler_min_lr: 1e-3 # minimum learning rate value
      scheduler_verbose: 5e-6 # print if learning rate is changed
  dataloader:
    train:
      shuffle: True # shuffle samples after every epoch
      num_workers: 4 # number of thread for dataloader1
    val:
      shuffle: False
      num_workers: 2
    test:
      shuffle: False
      num_workers: 2
  dataset:
    input_data: data_dir
    name: celeba # dataset name COVIDx or COVID_CT
    type: clf
    train:
      augmentation: True # do augmentation to video
    val:
      augmentation: False
    test:
      augmentation: False