trainer:
  cwd: /home/ # working directory
  logger: CNNS # logger name
  epochs: 100 # number of training epochs
  seed: 123 # randomness seed
  cuda: True # use nvidia gpu
  gpu: 0 # id of gpu
  save: True # save checkpoint
  batch_size: 64
  shape: 224
  load: True # load pretrained checkpoint
  gradient_accumulation: 1 # gradient accumulation steps
  pretrained_cpkt: /home/papastrat/PycharmProjects/CNNs/checkpoints/dataset_STL10/model_vit/date_30_04_2021_16.54.13/_backbone_last_checkpoint.pth.tar
  log_interval: 10000 # print statistics every log_interval
  model:
    name: vit # model name  [mobilenet_v2,COVIDNet_small]
    pretrained: False
    optimizer: # optimizer configuration
      type: Adam # optimizer type
      lr: 1e-4 # learning rate
      weight_decay: 0.000001 # weight decay
    scheduler: # learning rate scheduler
      type: ReduceLRonPlateau # type of scheduler
      scheduler_factor: 0.5 # learning rate change ratio
      scheduler_patience: 0 # patience for some epochs
      scheduler_min_lr: 1e-3 # minimum learning rate value
      scheduler_verbose: 5e-6 # print if learning rate is changed
  dataloader:
    train:
      batch_size: 128 # batch size
      shuffle: True # shuffle samples after every epoch
      num_workers: 4 # number of thread for dataloader1
    val:
      batch_size: 512
      shuffle: False
      num_workers: 2
    test:
      batch_size: 128
      shuffle: False
      num_workers: 2
  dataset:
    input_data: data_dir
    name: STL10 # dataset name COVIDx or COVID_CT
    type: clf
    train:
      augmentation: True # do augmentation to video
    val:
      augmentation: False
    test:
      augmentation: False